name: toNeko
version: '0.4.3'
main: com.crystalneko.toneko.ToNeko
api-version: '1.16'
author: CrystalNeko
softdepend: [ctLib]
folia-supported: true
commands:
  toneko:
    usage: /toneko help
    aliases: [cnk,tocat]
    description: toneko命令
  neko:
    usage: /neko help
    aliases: [cat]
    description: 猫娘命令
  aineko:
    usage: /aineko help
    description: AI猫娘命令
permissions:
  toneko.command.player:
    default: true
  toneko.command.item:
    default: true
  toneko.command.remove:
    default: true
  toneko.command.xp:
    default: true
  toneko.command.aliases:
    default: true
  toneko.command.reload:
    default: op
  neko.command.jump:
    default: true
    description: 跳跃提升
  neko.command.vision:
    default: true
    description: 夜视
  aineko.command.add:
    default: true
    description: 添加AI猫娘
  aineko.command.remove:
    default: true
    description: 删除AI猫娘
