name: toNeko
version: '${mod_version}'
main: org.cneko.toneko.bukkit.ToNeko
description: Turn players into nekos with AI chat, energy system, area/global chat, and more!
api-version: '1.21'
folia-supported: true
authors:
  - CrystalNeko
website: https://github.com/CSNeko/toNeko
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
permissions:
  command.tonekoadmin:
    default: op
  command.toneko:
    default: true
  command.neko:
    default: true
  command.quirk:
    default: true
