name: toNeko
version: '${mod_version}'
main: org.cneko.toneko.bukkit.ToNeko
api-version: '1.21'
authors:
  - CrystalNeko
  - MrHua269/Lora4967
  - QWERTY770
  - HappyRespawnanchor
  - ΗγΤζΡβΒι
  - homewool
  - pil0lo
  - yichifauzi
  - W.D.Water
folia-supported: true
depend: []
website: https://github.com/CSNeko/toNeko
description: 可爱即是正义!
commands:
  toneko:
    usage: /toneko help
    description: toNeko player commands
  tonekoadmin:
    usage: /tonekoadmin help
    description: toNeko admin commands
  neko:
    usage: /neko help
    description: Neko ability commands
  quirk:
    usage: /quirk help
    description: Quirk management commands
permissions:
  command.toneko:
    default: true
  command.toneko.help:
    default: true
  command.toneko.player:
    default: true
  command.toneko.accept:
    default: true
  command.toneko.deny:
    default: true
  command.toneko.remove:
    default: true
  command.toneko.alias:
    default: true
  command.toneko.block:
    default: true
  command.toneko.xp:
    default: true
  command.toneko.gui:
    default: true
  command.neko:
    default: true
  command.neko.help:
    default: true
  command.neko.chat:
    default: true
  command.neko.ride:
    default: true
  command.neko.ride_head:
    default: true
  command.neko.jump:
    default: true
  command.neko.speed:
    default: true
  command.neko.vision:
    default: true
  command.neko.lie:
    default: true
  command.neko.get_down:
    default: true
  command.neko.nickname:
    default: true
  command.neko.removeNickname:
    default: true
  command.neko.level:
    default: true
  command.neko.lore:
    default: true
  command.neko.gui:
    default: true
  command.quirk:
    default: true
  command.quirk.help:
    default: true
  command.quirk.list:
    default: true
  command.quirk.add:
    default: true
  command.quirk.remove:
    default: true
  command.quirk.gui:
    default: true
