name: toNeko
version: '1.3.6'
main: org.cneko.toneko.bukkit.ToNeko
api-version: '1.21'
author: CrystalNeko
depends: [ctLib]
folia-supported: true
commands:
  toneko:
    usage: /toneko help
    description: toneko命令
  tonekoadmin:
    usage: /tonekoadmin help
    description: toNeko管理员命令
permissions:
  command.toneko.help:
    default: true
  command.toneko.player:
    default: true
  command.toneko.remove:
    default: true