name: toNeko
version: '1.3.7'
main: org.cneko.toneko.bukkit.ToNeko
api-version: '1.21'
author: CrystalNeko
depends: [ctLib]
folia-supported: true
commands:
  toneko:
    usage: /toneko help
    description: toneko命令
  tonekoadmin:
    usage: /tonekoadmin help
    description: toNeko管理员命令
  neko:
    usage: /neko help
    description: 猫猫命令
permissions:
#  command.toneko.help:
#    default: true
#  command.toneko.player:
#    default: true
#  command.toneko.remove:
#    default: true
#  command.neko.help:
#    default: true
#  command.neko.ride:
#    default: true
  command.tonekoadmin:
    default: op
    children:
      command.tonekoadmin.help: true
      command.tonekoadmin.set: true
      command.tonekoadmin.reload: true
  command.toneko:
    default: true
    children:
      command.toneko.help: true
      command.toneko.player: true
      command.toneko.remove: true
      command.toneko.alias: true
      command.toneko.block: true
      command.toneko.xp: true
  command.neko:
    default: true
    children:
      command.neko.help: true
      command.neko.ride: true
      command.neko.get_down: true
      command.neko.lie: true
      command.neko.nickname: true
      command.neko.level: true
      command.neko.lore: true
      command.neko.vision: true
      command.neko.jump: true
      command.neko.speed: true